---
apiVersion: v1
kind: Service
metadata:
  namespace: thenamespace
  name: nginxfrontend
spec:
  selector:
    app: nginxfrontend
  ports:
  - port: 80
    name: nginxfrontend
    protocol: TCP
    targetPort: 80
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: thenamespace
  name: nginxfrontend
  labels:
    app: nginxfrontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginxfrontend
  template:
    metadata:
      labels:
        app: nginxfrontend
    spec:
      containers:
      - name: nginxfrontend
        image: nginx:{{.HASH}}
        ports:
        - containerPort: 80
        env:
        - name: NGINX_HOST # todo, change to a param
          value: "{{.NGINX_HOST}}"
        - name: NGINX_PORT # todo, change to a param
          value: "{{.NGINX_PORT}}"